spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    host: 59.110.67.133
    port: 5672
    username: tfan
    password: 9xgEKoiCGaf0#%xKITJC
    virtual-host: /
    publisher-confirm-type: correlated # 开启消息发送端确认
    publisher-returns: true # 开启消息抵达队列后确认
    template:
      mandatory: true # 只要抵达队列，异步回调确认
    listener:
      simple:
        acknowledge-mode: manual # 消费端手动确认消息
server:
  port: 8082

