spring:
  application:
    name: minio-demo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
minio:
  endpoint: http://localhost:9000
  accessKey: zyXfT5OyEpZbUn17HTc0
  secretKey: qn1U5nJDgnWJLnAa3QvVKcKMrEgWkD7dt3emfIEX
  bucketName: local-test
server:
  port: 8083