spring:
  application:
    name: spring-boot-consumer
dubbo:
  application:
    name: spring-boot-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false # 关闭注册时检查，否则会导致服务启动失败
  protocol:
    name: dubbo
    port: 20881
server:
  port: 8082
